version: '3.9'


services:

  innotter-db:
    container_name: innotter-db
    image: postgres:13.7-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - internship-net

  innotter-redis:
    container_name: innotter-redis
    image: redis:6-alpine
    ports:
      - "6380:6379"
    volumes:
      - .:/usr/src/volumes/redis
    networks:
      - internship-net

  innotter-celery:
    container_name: innotter-celery
    restart: always
    build:
      context: .
      network: host
    command: celery -A app worker -l info
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - innotter-redis
    networks:
      - internship-net

  innotter-celery-beat:
    container_name: innotter-celery-beat
    restart: always
    build:
      context: .
      network: host
    command: celery -A app beat -l info
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - innotter-redis
    networks:
      - internship-net

  innotter-app:
    container_name: innotter-app
    build:
      context: .
      network: host
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - innotter-celery
      - innotter-celery-beat
      - innotter-redis
      - innotter-db
    networks:
      - internship-net

networks:
  internship-net:
    driver: bridge
